apiVersion: v1
kind: Service
metadata:
  name: taskmaster-ikz-svc
  namespace: mongo
spec:
  selector:
    app: taskmaster-ikz
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30008
  type: NodePort