apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmaster-ikz
  namespace: mongo
  labels:
    app: taskmaster-ikz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmaster-ikz
  template:
    metadata:
      labels:
        app: taskmaster-ikz
    spec:
      containers:
        - name: taskmaster-ikz
          image: ikzdocker/task-api-flasgger:latest
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: apikey
                  key: API_KEY
          ports:
            - containerPort: 8080
          imagePullPolicy: Always