apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-llm
  namespace: agents
spec:
  selector:
    matchLabels:
      name: ollama-llm
  template:
    metadata:
      labels:
        name: ollama-llm
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "ollama-llm"
        dapr.io/enable-api-logging: "true"
        dapr.io/app-port: "11434"
        dapr.io/sidecar-inject: "true"
        dapr.io/sidecar-inject-annotation: "true"
    spec:
      containers:
      - name: ollama-llm
        image: ollama/ollama:latest
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
        lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "ollama run llama3.2:1b"]