apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: agents
spec:
  type: ClusterIP
  selector:
    name: ollama-llm
  ports:
  - port: 80
    name: http
    targetPort: http
    protocol: TCP