apiVersion: apps/v1
kind: Deployment
metadata:
  name: guess-wiki-questions-nodapr
  labels:
    app: guess-wiki-questions-nodapr
  namespace: agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guess-wiki-questions-nodapr
  template:
    metadata:
      labels:
        app: guess-wiki-questions-nodapr
      annotations:
        # dapr.io/enabled: "true"
        # dapr.io/app-id: "guess-film-noagent"
        # dapr.io/enable-api-logging: "true"
        # dapr.io/sidecar-inject: "true"
        # dapr.io/sidecar-inject-annotation: "true"
        # dapr.io/sidecar-liveness-probe-delay-second: "10"
        # dapr.io/sidecar-liveness-probe-timeout-seconds: "70"
    spec:
      containers:
      - name: guess-wiki-questions-nodapr
        image: ikzdocker/guesswiki-questions:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
